### ISSUE TITLE
非法侵入计算机信息系统罪

### ISSUE THREAD

**Issue by 3989** [SakuraKisser/AC_300fun#149]
在《中华人民共和国刑法》中，对危害网络安全行为定罪如下：
第二百八十五条 【非法侵入计算机信息系统罪】违反国家规定，侵入国家事务、国防建设、尖端科学技术领域的计算机信息系统的，处三年以下有期徒刑或者拘役

**Comment by zhl2008** [comment]
汪汪汪

**Comment by fireeyeusa** [comment]
Illegal Intrusion into Computer Information Systems？

**Comment by Earth-Spirit** [comment]
666
